"""Assemble advice input and generate advice through an LLMProvider."""

from __future__ import annotations

import json
from datetime import datetime
from importlib import resources
from pathlib import Path
from typing import Any, Callable

from lol_coach.context import build_advice_context
from lol_coach.llm import LLMProvider


def load_instructions() -> str:
    return resources.files("lol_coach").joinpath("prompts/advice.md").read_text(encoding="utf-8")


def find_previous_snapshot(output_dir: Path) -> Path | None:
    """Second newest `findings_*.json` (the newest one is the current run)."""
    snapshots = sorted(output_dir.glob("findings_*.json"))
    return snapshots[-2] if len(snapshots) >= 2 else None


def build_input(
    findings: dict[str, Any],
    *,
    practice_status: dict[str, Any] | None,
    matchup: dict[str, Any] | None,
    previous: dict[str, Any] | None,
) -> str:
    context = build_advice_context(
        findings, practice_status=practice_status, matchup=matchup, previous=previous
    )
    return json.dumps(context, ensure_ascii=False, separators=(",", ":"))


def generate_advice(
    provider: LLMProvider,
    *,
    instructions: str,
    input_text: str,
    output_dir: Path,
    on_delta: Callable[[str], object] = lambda _: None,
    now: Callable[[], datetime] = datetime.now,
) -> Path:
    """Stream advice, then save it. Nothing is written if the stream fails."""
    chunks: list[str] = []
    for delta in provider.stream(instructions=instructions, input_text=input_text):
        chunks.append(delta)
        on_delta(delta)
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"advice_{now():%Y%m%d_%H%M%S}.md"
    header = f"<!-- generated by lol-tools advise (model: {provider.model}) -->\n\n"
    path.write_text(header + "".join(chunks), encoding="utf-8")
    return path
